version: '3.8'

# Включаем все сервисы из отдельных файлов
include:
  - docker-compose/mysql.yml
  - docker-compose/event-ingest.yml
  - docker-compose/shard-splitter.yml
  - docker-compose/shard-workers.yml
  - docker-compose/balance-daemon.yml
 # - docker-compose/cache-service.yml
 # - docker-compose/tests.yml
